name       : gtkwave
version    : 3.3.103
release    : 2
source     :
    - http://gtkwave.sourceforge.net/gtkwave-gtk3-3.3.103.tar.gz : 5e25f2fe8474bdb1e7651b86ddcd79f2c0b8b455a55a4ec84d4a9ce3bb755836
homepage   : http://gtkwave.sourceforge.net
license    : GPL-2.0-or-later
component  : office.scientific
summary    : a fully featured GTK+ based wave viewer
description: |
    GTKWave is a fully featured GTK+ based wave viewer for Unix, Win32, and Mac OSX which reads LXT, LXT2, VZT, FST, and GHW files as well as standard Verilog VCD/EVCD files and allows their viewing.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gconf-2.0)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - gperf
    - bzip2-devel
patterns   :
    - docs :
        - /usr/share/gtkwave
setup      : |
    %configure --enable-gtk3 --with-gconf
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/gtkwave-gtk3 $installdir/usr/share/gtkwave
