name       : gtkwave
version    : 3.3.89
release    : 1
source     :
    - http://gtkwave.sourceforge.net/gtkwave-3.3.89.tar.gz : af10558beed7cec6758fcd4bca989cec117589def29d709b31eaaa3a81f7ebc8
license    : GPL-2.0-or-later
component  : office.scientific
summary    : a fully featured GTK+ based wave viewer
description: |
    GTKWave is a fully featured GTK+ based wave viewer for Unix, Win32, and Mac OSX which reads LXT, LXT2, VZT, FST, and GHW files as well as standard Verilog VCD/EVCD files and allows their viewing.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gconf-2.0)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - bzip2-devel
    - gperf
patterns   :
    - docs :
        - /usr/share/gtkwave
setup      : |
    %configure --with-gconf
build      : |
    %make
install    : |
    %make_install